### ISSUE TITLE
README being cut off

### ISSUE THREAD

**Issue by telephone** [KnightSwarm/Minstall#3]
Under the section "Download Minstall" the text for a one line install is being cut-off prematurely:

`cd ~; rm -rf minstall minstall.tar.gz; mkdir minstall; cd minstall; wget --no-check-certificate -O minstall.tar.gz http://www`

**Comment by maxexcloo** [comment]
If you double click the line it'll copy the full text.

cd ~; rm -rf minstall minstall.tar.gz; mkdir minstall; cd minstall; wget --no-check-certificate -O minstall.tar.gz http://www.github.com/downloads/KnightSwarm/Minstall/Latest.tar.gz; tar zxvf minstall.tgz

That said, I will clean that up!
