### ISSUE TITLE
Web Application Installation Modules

### ISSUE THREAD

**Issue by maxexcloo** [KnightSwarm/Minstall#36]
Things like Wordpress, etc

**Comment by Noerman** [comment]
Any known CMS maybe, but WordPress great for start. This optimization involves installation of WordPress & the Nginx config.

**Comment by maxexcloo** [comment]
I've made one for Wordpress, no nginx configuration yet.

**Comment by maxexcloo** [comment]
Keeping it simple ;)
Will do things as they come!
