### ISSUE TITLE
"Clean Packages" Attempts to Remove Essential Packages

### ISSUE THREAD

**Issue by thesupremecommander** [KnightSwarm/Minstall#43]
Error is caused by a failure in parsing one of the selection lists:
`dpkg: error: unexpected end of line in package name at line 1`

Resulting in:

```
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  apt libapt-pkg4.12 (due to apt) libstdc++6 (due to apt)
  debian-archive-keyring (due to apt) gnupg (due to apt) base-files bash
```

Steps to reproduce: run Clean Packages module (`minstall -m clean-packages`).
System: 128MB CVZ-E5 VPS on RamNode, running from Debian 6 x32 image upgraded to Debian 7.

**Comment by thesupremecommander** [comment]
Issue can be fixed by correcting line 16 in `libraries/platform/clean.debian.sh` from:

``` shell
dpkg --set-selections < temp.list
```

to:

``` shell
dpkg --set-selections < temp.dpkg
```

**Comment by maxexcloo** [comment]
The whole clean packages function is currently undergoing a major rework as
Debian 7 threw everything I knew away!
I'll leave this open till I have a proper look and fix it.

**Comment by thesupremecommander** [comment]
Well, that fix seemed to work for the most part, except for when `apt-get dist-upgrade` tries to throw upstart away and replace it with sysvinit. I'm not sure which you meant to have on the system. After a while clean-packages also fails with errors when creating a new list of packages.

**Comment by maxexcloo** [comment]
I had it working yesterday in dpkg on Debian 7 x86 but everything broke
when I tested it on 64 bit. As a result I was testing some code out ;)
Master isn't stable (although I love bug reports!)

**Comment by thesupremecommander** [comment]
Well, eventually I have to get this VPS working, but might as well improve Minstall while I'm at it.

If it's breaking on x64, is it perhaps an architecture problem? That's the only difference I remember from the code, the addition of the i386 architecture to dpkg.

**Comment by maxexcloo** [comment]
Debian 7 adds multi arch support (along with a broken dpkg implantation,
:/) and this seems to break everything. I'm probably going to have to sit
down and make another package list to compare ;)

**Comment by maxexcloo** [comment]
Oh man this is embarrassing, I have to apologise! In my tired state I misread your fix, you are indeed right!
Thanks for this one!
