### ISSUE TITLE
Multiple Packages Not Installing

### ISSUE THREAD

**Issue by thesupremecommander** [KnightSwarm/Minstall#44]
Problem: when multiple packages are installed at once in the script, the package installer fails with the error that the packages concatenated could not be found, such as "php5-cli php5-fpm".

Fix: change line 19 of libraries/platform/package.debian.sh to

``` shell
apt-get -qy install "$@"
```

which probably is the intention here.

**Comment by maxexcloo** [comment]
Thanks for the fix, I'll add it when I'm next at my PC!

**Comment by maxexcloo** [comment]
Fixed.
