### ISSUE TITLE
Debian 7 - upstart/sysvinit

### ISSUE THREAD

**Issue by thesupremecommander** [KnightSwarm/Minstall#46]
Since `sysvinit` is marked as an essential package, `apt-get` refuses to remove it without `--force-yes`. This is an issue because the Debian 7 package lists include `upstart` and not `sysvinit`.

The solution is either to change `upstart` to `sysvinit` or run the `apt-get` command with `--force-yes`.

**Comment by maxexcloo** [comment]
I'm not experiencing this issue unfortunately, mind sharing your test environment?

**Comment by thesupremecommander** [comment]
Debian 7 32-bit freshly installed image on RamNode.

**Comment by maxexcloo** [comment]
Awesome! Mind telling me about the server specs? I also need to look into
64 bit support ;)

**Comment by thesupremecommander** [comment]
It's the 128MB CVZ plan.

I'll try again and see if the issue persists.

**Comment by thesupremecommander** [comment]
I have not reproduced this issue recently... it may be an image issue. Should be reopened if someone can reproduce it.
