### ISSUE TITLE
clean-packages Fails After Running install-extra-repositories

### ISSUE THREAD

**Issue by thesupremecommander** [KnightSwarm/Minstall#48]
For some reason `clean-packages` works perfectly on a fresh Debian 7 image, but running `install-extra-repositories` first and nothing else causes `clean-packages` to bug out with:

```
dpkg: error: unexpected data after package and selection at line 14
```

This causes `apt-get` to attempt to remove all packages on the system and thus fail.

**Comment by maxexcloo** [comment]
Very odd, I had success this afternoon when testing, mind adding me on
Skype or something so we can debug over chat? I'm maxexcloo.

**Comment by thesupremecommander** [comment]
Found the issue!

In `modules/install-extra-repositories/debian-7/debian-multimedia.sh`, to prevent the `deb-multimedia-keyring` package from being uninstalled by `clean-packages` you have the following command:

```
    echo "deb-multimedia-keyring install" >> $MODULEPATH/clean-packages/custom/custom
```

However, `libraries/platform/clean.debian-7.sh` adds on another "install" before running the selections through dpkg, thus causing dpkg to fail because of the syntax error.

The solution is to remove the "install" from the end of the line.

Issue also spotted in `modules/install-extra-repositories/ubuntu/medibuntu.sh`.

**Comment by maxexcloo** [comment]
Fixed, thanks!
