### ISSUE TITLE
nginx default configuration

### ISSUE THREAD

**Issue by mikho** [KnightSwarm/Minstall#5]
after installing nginx the file: /etc/nginx/hosts.d/default.conf

has the entry 
root /usr/share/nginx/www;

This directory does not exist, however the directory : root /usr/share/nginx/html does.

Updating the default.conf resolves this issue.

**Comment by maxexcloo** [comment]
Is this on Debian or Ubuntu?

**Comment by mikho** [comment]
debian

**Comment by maxexcloo** [comment]
Fixed!
