### ISSUE TITLE
Links To Look Into

### ISSUE THREAD

**Issue by maxexcloo** [KnightSwarm/Minstall#50]
http://stackoverflow.com/questions/2953081/how-can-i-write-a-here-doc-to-a-file-in-bash-script
http://stackoverflow.com/questions/415677/how-to-replace-placeholders-in-a-text-file
https://news.ycombinator.com/item?id=5905966
http://www.reddit.com/r/linux/comments/1hb3by/securing_a_linux_home_server/
https://baudehlo.wordpress.com/2013/06/24/setting-up-perfect-forward-secrecy-for-nginx-or-stud/
https://news.ycombinator.com/item?id=5954984
http://stackoverflow.com/questions/2297533/what-is-the-proper-indentation-for-bash-scripts
https://news.ycombinator.com/item?id=6040381
http://dghubble.com/.bashprofile-.profile-and-.bashrc-conventions.html
http://robots.thoughtbot.com/post/2641409235/a-tmux-crash-course/

**Comment by maxexcloo** [comment]
http://news.ycombinator.com/item?id=6456724

**Comment by thesupremecommander** [comment]
Going off of a tangent off that link, the official repository would definitely fix the broken dependency issues in DotDeb that are a pain to deal with in Wheezy and that so far they've refused to fix.
