### ISSUE TITLE
Add Option in User Configuration for SSH/SFTP

### ISSUE THREAD

**Issue by thesupremecommander** [KnightSwarm/Minstall#58]
Currently users that are created cannot SSH or SFTP in because they are not in the required groups.

Configuration options should be added to:
- allow/deny the user to SSH in
- if above is allowed, restrict user to SFTP only

**Comment by maxexcloo** [comment]
I need to add this to the user management module.

**Comment by thesupremecommander** [comment]
Fixed in 4e5c05bf51a0f7d7948aa0597ee93560aa34e119.
