### ISSUE TITLE
installation using new version

### ISSUE THREAD

**Issue by kensim86** [KnightSwarm/Minstall#67]
hello, may I know how do I run the scripts that is in the master branch? I followed the instructions from the previous branch, but it does not work. Thanks!

**Comment by thesupremecommander** [comment]
From what I remember, `minstall -s` sets up Minstall for use (needed for some modules to properly function). `minstall -l` will list the available modules for use. Once you know which module to use, `minstall -m MODULE-NAME` will run the module.

**Comment by kensim86** [comment]
ah icic. thanks! but just wondering, did i miss it out in the documentation?

**Comment by thesupremecommander** [comment]
I don't think it's documented at the moment. That probably should be added.
