### ISSUE TITLE
User Module Support for sudo

### ISSUE THREAD

**Issue by thesupremecommander** [KnightSwarm/Minstall#69]
There probably should be an option in the user management module for allowing/denying a user access to sudo via adding/removing membership in the sudo group.

**Comment by maxexcloo** [comment]
While minstall is unsupported now I can probably put this together some
time (unless you want to put in a pull request that is), definitely a good
idea!

**Comment by thesupremecommander** [comment]
I'll probably put in a pull request later, just wanted to put the issue up.
